#!/bin/bash

homedir=~
eval homedir=$homedir

if [ "$#" -eq 0 ] ; then
  echo -e "Usage:"
  echo "./doall <ProcessJ source file path>"
  echo "    - compiles .pj file and generates .java files in workspace defined in .pjconfig"
  echo "    - compiles generated .java file"
  echo "    - instruments .class file/s"
  echo "    - creates executable jar file"
  echo " -------------------------------"
  echo "./doall -java"
  echo "    - compiles .java file in the workspace defined in .pjconfig"
  echo "    - instruments .class file/s"
  echo "    - creates executable jar file"
  exit 0
fi

CONFIG_FILE=".pjconfig"
if ! [ -e "$homedir/$CONFIG_FILE" ] ; then
  echo "No ProcessJ configuration file found. Should be in '$homedir/$CONFIG_FILE'"
  exit
fi
CONFIG_FILE="$homedir/$CONFIG_FILE"

if ! grep "workingdir" "$CONFIG_FILE" > /dev/null ; then
  echo "No working directory specified in '$CONFIG_FILE'."
  echo "File must contain a line of the form 'workingdir=...'"
  exit
fi

workingdir="$homedir/`grep workingdir $CONFIG_FILE | cut -d '=' -f 2 | sed 's/ //g'`"
echo "the working directory is $workingdir"

if ! [ -d "$workingdir" ] ; then
  echo "Working directory '$workingdir' missing. "
  read -r -p "Make '$workingdir'? [y/n] " response
  case $response in
  [yY])
    mkdir $workingdir
    chmod 755 $workingdir
    ;;
  *)
    echo "Working directory not created"
    exit
    ;;
  esac
fi

if [ "$#" -ne 2 ] ; then
  ## clean the working directory
  rm -i -rf $workingdir/* > /dev/null

  ## compile .pj code using ProcessJ compiler and generate the .java file in the working directory.
  java -cp bin:src/Utilities/java_cup_runtime.jar:src/Utilities/ST-4.0.7.jar:src/Utilities/asm-all-3.3.1.jar:lib/JVM:. ProcessJc -t JVM $1

  ## let's create an executable jar file now.
  mkdir $workingdir/META-INF ## create dir for manifest file
  filename="${1##*/}" ## $@ is the full path'ed filename of .pj file. we extract just the file name x.pj
  just_filename="${filename%.*}" ## now extract just the name of the file
fi

## compile the .java file using Java compiler
javac -classpath bin/:lib/JVM:. $workingdir/*.java

## instrument the Java classes for resumption
java -classpath bin/:src/Utilities/asm-all-3.3.1.jar:. Instrument/Instrumenter $workingdir

echo "Main-Class: "$just_filename > $workingdir/META-INF/MANIFEST.MF ## write the manifest file

jar cmvf $workingdir/META-INF/MANIFEST.MF $workingdir/$just_filename.jar $workingdir/*.class ## create the jar file

