#! /bin/bash

echo compiling!
gcc -O3 -g -std=c99 -L CCSP/bin/  -I CCSP/include -fomit-frame-pointer -fno-defer-pop -m32 -DKROC_USES_PTHREADS codeGenerated.c -o codeGenerated -lpthread -lccsp -Wl,-rpath,CCSP/bin/
