#! /bin/bash

echo compiling!
gcc -O0 -g -std=c99 -fstack-usage -L lib/CCSP/lib/  -I lib/CCSP/include/kroc -fomit-frame-pointer -fno-defer-pop -m32 -DKROC_USES_PTHREADS codeGenerated.c -o codeGenerated -lccsp -lpthread -Wl,-rpath,lib/CCSP/lib/
