#!/bin/bash                                                                                                                                                                                                                         
INSTALL_DIR="<<INSTALL_DIR>>"

if [ $# -eq 0 ] ; then
  echo "Usage: pj filename"
  exit 1;
fi

java -cp $INSTALL_DIR/bin/:$INSTALL_DIR/lib/JVM:$@.jar $@
