
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Oct 02 14:17:29 PDT 2015
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 4;
  public static final int TIMEOUT = 21;
  public static final int IDENTIFIER = 112;
  public static final int ANDEQ = 76;
  public static final int TIMER = 20;
  public static final int GT = 79;
  public static final int IMPLEMENTS = 47;
  public static final int CLAIM = 16;
  public static final int ENROLL = 19;
  public static final int READ = 13;
  public static final int CONST = 55;
  public static final int NOTEQ = 84;
  public static final int BARRIER = 17;
  public static final int PLUSEQ = 71;
  public static final int RBRACK = 64;
  public static final int ALT = 38;
  public static final int COMMA = 66;
  public static final int DOUBLE_LITERAL = 109;
  public static final int RBRACE = 62;
  public static final int RPAREN = 60;
  public static final int LBRACK = 63;
  public static final int LT = 80;
  public static final int ANDAND = 88;
  public static final int OROR = 89;
  public static final int DOUBLE = 8;
  public static final int LBRACE = 61;
  public static final int RRSHIFT = 87;
  public static final int LPAREN = 59;
  public static final int XOREQ = 77;
  public static final int PROTECTED = 54;
  public static final int INTEGER_LITERAL = 106;
  public static final int NOT = 98;
  public static final int STOP = 23;
  public static final int FLOAT = 7;
  public static final int PROC = 43;
  public static final int PACKAGE = 48;
  public static final int COMP = 99;
  public static final int SYNC = 18;
  public static final int RECORD = 45;
  public static final int EQ = 67;
  public static final int MOD = 97;
  public static final int RESUME = 40;
  public static final int BOOLEAN_LITERAL = 57;
  public static final int WRITE = 14;
  public static final int NATIVE = 51;
  public static final int LONG_LITERAL = 107;
  public static final int PLUS = 90;
  public static final int LONG = 6;
  public static final int WHILE = 27;
  public static final int EXTENDS = 46;
  public static final int PAR = 36;
  public static final int CHAR = 9;
  public static final int BOOLEAN = 2;
  public static final int CHAN = 12;
  public static final int SWITCH = 28;
  public static final int DO = 30;
  public static final int SKIP = 22;
  public static final int FOR = 26;
  public static final int RSHIFTEQ = 74;
  public static final int DIV = 93;
  public static final int VOID = 11;
  public static final int EXTERN = 56;
  public static final int MULT = 92;
  public static final int PUBLIC = 52;
  public static final int RETURN = 34;
  public static final int ELSE = 25;
  public static final int GTEQ = 83;
  public static final int BREAK = 32;
  public static final int DOT = 105;
  public static final int INT = 5;
  public static final int PRAGMA = 58;
  public static final int STRING_LITERAL = 110;
  public static final int EQEQ = 81;
  public static final int EOF = 0;
  public static final int SEMICOLON = 65;
  public static final int DEFAULT = 31;
  public static final int MULTEQ = 68;
  public static final int IMPORT = 49;
  public static final int MINUS = 91;
  public static final int SUSPEND = 41;
  public static final int FLOAT_LITERAL = 108;
  public static final int LTEQ = 82;
  public static final int OR = 95;
  public static final int error = 1;
  public static final int DIVEQ = 69;
  public static final int SEQ = 35;
  public static final int LSHIFTEQ = 73;
  public static final int CONTINUE = 33;
  public static final int IF = 24;
  public static final int PRI = 37;
  public static final int MODEQ = 70;
  public static final int MINUSMINUS = 101;
  public static final int COLON = 103;
  public static final int MOBILE = 50;
  public static final int CHARACTER_LITERAL = 111;
  public static final int COLONCOLON = 104;
  public static final int OREQ = 78;
  public static final int QUEST = 102;
  public static final int PLUSPLUS = 100;
  public static final int CASE = 29;
  public static final int NEW = 39;
  public static final int RSHIFT = 86;
  public static final int STRING = 10;
  public static final int SHARED = 15;
  public static final int BYTE = 3;
  public static final int AND = 94;
  public static final int PRIVATE = 53;
  public static final int LSHIFT = 85;
  public static final int WITH = 42;
  public static final int XOR = 96;
  public static final int RRSHIFTEQ = 75;
  public static final int MINUSEQ = 72;
  public static final int PROTOCOL = 44;
}

